### ISSUE TITLE
Play/Pause button doesn't work

### ISSUE THREAD

**Issue by neonichu** [calebd/cloudy#5]
Seems like the new JS merged in #3 broke it - the version before that works.

**Comment by calebd** [comment]
You're right. Working on it...

**Comment by neonichu** [comment]
Awesome!

![](https://camo.githubusercontent.com/14a1786d1ff13fb8cd09be28e81f92f193b98efd/687474703a2f2f692e696d6775722e636f6d2f6f313273492e676966)
